### ISSUE TITLE
"make dist" and "./make_tar.sh" are both broken in spielwiese HEAD

### ISSUE THREAD

**Issue by mkoeppe** [Singular/Singular#1016]
1) `make dist` (https://github.com/mkoeppe/Sources/runs/842806845):
```
config.status: creating 'config.h' - prefix '' for '_config.h' defines
config.status: executing libtool commands
make  dist-gzip am__post_remove_distdir='@:'
make[1]: *** No rule to make target 'doc/doc.tbz2', needed by 'distdir'.  Stop.
make[1]: Entering directory '/home/runner/work/Sources/Sources/build/pkgs/singular/src'
make[1]: Leaving directory '/home/runner/work/Sources/Sources/build/pkgs/singular/src'
make: *** [dist] Error 2
Makefile:853: recipe for target 'dist' failed
```

2) `./make_tar.sh` is missing the executable flag (https://github.com/mkoeppe/Sources/runs/842834597):
```
Run (cd build/pkgs/singular/src && ./make_tar.sh) \
/home/runner/work/_temp/b7e29dea-1d9c-42dc-af31-5b964fe219d6.sh: line 1: ./make_tar.sh: Permission denied
```

3) `./make_tar.sh` refers to some local files (https://github.com/mkoeppe/Sources/runs/842839994)
```
Run (cd build/pkgs/singular/src && bash ./make_tar.sh) \
autoreconf: Entering directory `.'
...
./configure
./factory/configure
/home/runner/work/Sources/Sources/build/pkgs/singular/src/singular-4.1.3
cp: cannot stat 'redhat/singular.spec': No such file or directory
cp: cannot stat '/tmp2/wawa-i/share/singular/LIB/all.lib': No such file or directory
```

**Comment by fingolfin** [comment]
AFAIK (but @hannes14 will correct me if I am wrong), Singular simply doesn't make use of `make dist`. (If that is true, I think `no-dist` should be added to `AM_INIT_AUTOMAKE`, to disable `make dist` and hence avoid confusion).

Secondly, right now, preparing a release involves a lot of Voodoo (e.g. to build the documentation the right way); I think only @hannes14 knows how to do that, so yeah, `make_tar.sh` is not usable by just anybody...

I really would like to see this changed, in particular it would be great if we could use more automation for the release process, so that we can have more frequent releases without overburdening @hannes14 . Also, when he retires some day, we need to still be able to make releases :-).

**Comment by mkoeppe** [comment]
Thanks for the reaction.

> AFAIK (but @hannes14 will correct me if I am wrong), Singular simply doesn't make use of `make dist`. (If that is true, I think `no-dist` should be added to `AM_INIT_AUTOMAKE`, to disable `make dist` and hence avoid confusion).

+1

> Secondly, right now, preparing a release involves a lot of Voodoo (e.g. to build the documentation the right way); I think only @hannes14 knows how to do that, so yeah, `make_tar.sh` is not usable by just anybody...
> 
> I really would like to see this changed, in particular it would be great if we could use more automation for the release process, so that we can have more frequent releases without overburdening @hannes14 . Also, when he retires some day, we need to still be able to make releases :-).

+1. Automating the release process -- so that ultimately making a release is as easy as pushing an annotated tag -- vastly reduces the maintenance burden and makes making a new release less of a big deal.

**Comment by mkoeppe** [comment]
With the latest changes in spielwiese, `make_tar.sh` fails harder.
{{{
./factory/configure
/home/runner/work/Sources/Sources/build/pkgs/singular/src/singular-4.1.3
cp: cannot stat '/tmp2/wawa/redhat/singular.spec': No such file or directory
#
}}}
This is not an improvement

**Comment by mkoeppe** [comment]
Thanks for improving the documentation of `make_tar.sh` in 063360e72, which led me to try `make dist` again, which has apparently been fixed (https://github.com/mkoeppe/Sources/runs/910246018), thank you.
