### ISSUE TITLE
Segment fault using nc_algebra

### ISSUE THREAD

**Issue by gblanco92** [Singular/Singular#1051]
The commit 4470c0e32fbd88486ac477ef7c9a7a70bf64e46e produces the following segmentation fault:

> Singular : signal 11 (v: 4201):
> current line:>>  def @R = nc_algebra(1,@D);<<
> Segment fault/Bus error occurred at 7fbc08f5d148 because of 10206 (r:1614090875)
> please inform the authors
> trying to restart...
>    ? @R is no name of a ring/qring
>    ? error occurred in or before dmod.lib::SannfsBM line 3307: `  setring @R;`
>    ? leaving dmod.lib::SannfsBM (3303)

This only happens if `autogen.sh` is executed before building from scratch. If one uses a previous build environment from a previous commit everything works fine.

Code to reproduce the crash:

`./build/Singular/Singular --quiet --no-out --execute='LIB "dmod.lib"; ring R=0,(x,y),dp; poly f=y^2-x^3; def D=SannfsBM(f); quit;'`

**Comment by hannes14** [comment]
That commit does not change anything in the sources,
it only restructures the build system (which and how libraries for parts are built).
So it would be very surprising if it would result in seg fault (does not happen here).
Possibly some remainings of a previous build?

**Comment by gblanco92** [comment]
No, it is working if I do a **clean** build using the previous commit. A **clean** build in this commit, I get the segfault. However, if I reuse the build from a previous commit then it works fine. This is tested with both gcc-7 & gcc-9.

Changing the link order may expose some underlaying bug, it is rare but it may happen.

**Comment by hannes14** [comment]
The link order is not changed, what is changed is: instead of several separate libraries (libmisc, librepoerter, libpolys) there is now only one library: libpolys.
Maybe, there are 2 procedures with exactly the same name and your linker chooses the wrong one
(which  is obviously a bug but difficult to find if it does not crash)
Can you build a debug version and tell the backtrace of the crash?
(
export CFLAGS="-g -pipe -fno-common -fno-exceptions"
export CXXFLAGS="-g -pipe -fno-common -fno-exceptions -fno-rtti"
configure -C --enable-debug --disable-optimizationflags 
)

**Comment by gblanco92** [comment]
> Singular : signal 11 (v: 4201):
> current line:>>  def @R = nc_algebra(1,@D);<<
> Segment fault/Bus error occurred at 7f2f133df500 because of 10206 (r:1614164059)
> please inform the authors
> 
> 
> quit with "p si_stop_stack_trace_x=0"
> 
> 
> GNU gdb (Ubuntu 8.2-0ubuntu1~18.04) 8.2
> Copyright (C) 2018 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> Type "show copying" and "show warranty" for details.
> This GDB was configured as "x86_64-linux-gnu".
> Type "show configuration" for configuration details.
> For bug reporting instructions, please see:
> <http://www.gnu.org/software/gdb/bugs/>.
> Find the GDB manual and other documentation resources online at:
>     <http://www.gnu.org/software/gdb/documentation/>.
> 
> For help, type "help".
> Type "apropos word" to search for commands related to "word"...
> Reading symbols from Singular...done.
> Attaching to program: /home/guillem/Singular/build/Singular/Singular, process 32385
> Reading symbols from /lib/x86_64-linux-gnu/libdl.so.2...Reading symbols from /usr/lib/debug//lib/x86_64-linux-gnu/libdl-2.27.so...done.
> done.
> Reading symbols from /usr/lib/libflint-2.5.2.so...(no debugging symbols found)...done.
> Reading symbols from /usr/lib/libntl.so.35...(no debugging symbols found)...done.
> Reading symbols from /lib/x86_64-linux-gnu/libreadline.so.7...(no debugging symbols found)...done.
> Reading symbols from /usr/lib/x86_64-linux-gnu/libmpfr.so.6...(no debugging symbols found)...done.
> Reading symbols from /usr/lib/x86_64-linux-gnu/libgmp.so.10...(no debugging symbols found)...done.
> Reading symbols from /lib/x86_64-linux-gnu/libpthread.so.0...Reading symbols from /usr/lib/debug/.build-id/68/f36706eb2e6eee4046c4fdca2a19540b2f6113.debug...done.
> done.
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
> Reading symbols from /usr/lib/x86_64-linux-gnu/libstdc++.so.6...(no debugging symbols found)...done.
> Reading symbols from /lib/x86_64-linux-gnu/libm.so.6...Reading symbols from /usr/lib/debug//lib/x86_64-linux-gnu/libm-2.27.so...done.
> done.
> Reading symbols from /lib/x86_64-linux-gnu/libgcc_s.so.1...(no debugging symbols found)...done.
> Reading symbols from /lib/x86_64-linux-gnu/libc.so.6...Reading symbols from /usr/lib/debug//lib/x86_64-linux-gnu/libc-2.27.so...done.
> done.
> Reading symbols from /lib64/ld-linux-x86-64.so.2...Reading symbols from /usr/lib/debug//lib/x86_64-linux-gnu/ld-2.27.so...done.
> done.
> Reading symbols from /usr/lib/x86_64-linux-gnu/libgf2x.so.1...(no debugging symbols found)...done.
> Reading symbols from /lib/x86_64-linux-gnu/libtinfo.so.5...(no debugging symbols found)...done.
> Reading symbols from /usr/local/libexec/singular/MOD/singmathic.so...(no debugging symbols found)...done.
> Reading symbols from /usr/local/libexec/singular/MOD/p_Procs_FieldIndep.so...(no debugging symbols found)...done.
> Reading symbols from /usr/local/libexec/singular/MOD/p_Procs_FieldQ.so...(no debugging symbols found)...done.
> 0x00005569a97716a0 in debug (method=0) at ../../Singular/cntrlc.cc:426
> 426       while (si_stop_stack_trace_x) ;
> (gdb) bt
> #0  0x00005569a97716a0 in debug (method=0) at ../../Singular/cntrlc.cc:426
> #1  0x00005569a97712b5 in sigsegv_handler (sig=11, s=...) at ../../Singular/cntrlc.cc:199
> #2  <signal handler called>
> #3  0x00007f2f12d087fc in p_Copy__FieldQ_LengthFive_OrdGeneral () from /usr/local/libexec/singular/MOD/p_Procs_FieldQ.so
> #4  0x00005569a9aec53b in p_Copy_noCheck (p=0x7f2f133df4c8, r=0x7f2f133de160) at ../../libpolys/polys/monomials/p_polys.h:808
> #5  0x00005569a9aec57f in p_Copy (p=0x7f2f133df4c8, r=0x7f2f133de160) at ../../libpolys/polys/monomials/p_polys.h:817
> #6  0x00005569a9af7f13 in nc_p_CopyGet (a=0x7f2f133df4c8, r=0x7f2f133de160) at ../../libpolys/polys/nc/old.gring.cc:2539
> #7  0x00005569a9af84b4 in gnc_CheckOrdCondition (D=0x7f2f1333b0c0, r=0x7f2f133de160) at ../../libpolys/polys/nc/old.gring.cc:2645
> #8  0x00005569a9af9610 in nc_CallPlural (CCC=0x0, DDD=0x7f2f1333b090, CCN=0x7f2f133df0d8, DDN=0x0, r=0x7f2f133de160, bSetupQuotient=false,
>     bCopyInput=true, bBeQuiet=false, curr=0x7f2f133ce518, dummy_ring=false) at ../../libpolys/polys/nc/old.gring.cc:2964
> #9  0x00005569a978a799 in jjPlural_num_mat (res=0x7ffcf22d11b0, a=0x7f2f133daae8, b=0x7f2f133dabe8) at ../../Singular/iparith.cc:2815
> #10 0x00005569a979f34b in iiExprArith2TabIntern (res=0x7ffcf22d11b0, a=0x7ffcf22d14d8, op=461, b=0x7ffcf22d1548, proccall=1,
>     dA2=0x5569a9f72990 <dArith2+7824>, at=419, bt=277, dConvertTypes=0x5569a9f6e3c0 <dConvertTypes>) at ../../Singular/iparith.cc:8479
> #11 0x00005569a979faf3 in iiExprArith2 (res=0x7ffcf22d11b0, a=0x7ffcf22d14d8, op=461, b=0x7ffcf22d1548, proccall=1)
>     at ../../Singular/iparith.cc:8621
> #12 0x00005569a9779224 in yyparse () at grammar.y:598
> #13 0x00005569a97b1f62 in iiAllStart (pi=0x7f2f13341d28,
>     p=0x7f2f133d3068 "parameter poly F; parameter list #;  \n  int eng = 0;\n  if ( size(#)>0 )\n  {\n    if ( typeof(#[1]) == \"int\" )\n    {\n      eng = int(#[1]);\n    }\n  }\n  // returns a list with a ring and an ideal LD in i"..., t=BT_proc, l=3227) at ../../Singular/iplib.cc:310
> #14 0x00005569a97b23ef in iiPStart (pn=0x7f2f133504e8, v=0x7f2f133ccce8) at ../../Singular/iplib.cc:416
> #15 0x00005569a97b2a61 in iiMake_proc (pn=0x7f2f133504e8, pack=0x0, args=0x7f2f133ccce8) at ../../Singular/iplib.cc:547
> #16 0x00005569a978619f in jjPROC (res=0x7ffcf22d4490, u=0x7f2f133ccc68, v=0x7f2f133ccce8) at ../../Singular/iparith.cc:1630
> #17 0x00005569a979f34b in iiExprArith2TabIntern (res=0x7ffcf22d4490, a=0x7ffcf22d4748, op=40, b=0x7f2f133ccbe8, proccall=0,
>     dA2=0x5569a9f71e80 <dArith2+4992>, at=271, bt=280, dConvertTypes=0x5569a9f6e3c0 <dConvertTypes>) at ../../Singular/iparith.cc:8479
> #18 0x00005569a979faf3 in iiExprArith2 (res=0x7ffcf22d4490, a=0x7ffcf22d4748, op=40, b=0x7f2f133ccbe8, proccall=0)
>     at ../../Singular/iparith.cc:8621
> #19 0x00005569a979a413 in jjKLAMMER_PL (res=0x7ffcf22d4490, u=0x7ffcf22d4748) at ../../Singular/iparith.cc:7615
> #20 0x00005569a97a18f2 in iiExprArithM (res=0x7ffcf22d4490, a=0x7ffcf22d4748, op=40) at ../../Singular/iparith.cc:9143
> #21 0x00005569a9778b14 in yyparse () at grammar.y:480
> #22 0x00005569a9770121 in main (argc=4, argv=0x7ffcf22d83e8) at ../../Singular/tesths.cc:233

**Comment by hannes14** [comment]
Funny, no dupplicate procedure names in the call chain.
I could not find the bug, but I do not insist on the changes to libpolys, so I reverted it.

**Comment by gblanco92** [comment]
The current HEAD of spielwiese works fine for me now.
