### ISSUE TITLE
subst is leaking memory

### ISSUE THREAD

**Issue by videlec** [Singular/Singular#1089]
The following commands fill up the memory very quickly
```
ring r=0,(x,y),dp;
poly p=(x+y)^10;
poly q;
while (1) { q = subst(p,x,x+y); }
```

(this shows up in SageMath https://trac.sagemath.org/ticket/27261)

**Comment by dimpase** [comment]
By "quickly", one really means quckly, one reaches many GB of RAM taken by the Singular process in <20 seconds.

**Comment by dimpase** [comment]
ping?

**Comment by hannes14** [comment]
see c23373ad2d265e3205a614eef4bd2533255b1902

**Comment by videlec** [comment]
Is it better to report a bug via the trac server?

**Comment by hannes14** [comment]
both is possible, trac is prefered

**Comment by dimpase** [comment]
trac has a problem that users cannot comment/edit, they can only open tickets.

**Comment by dimpase** [comment]
The example here came from an attempt to reproduce an apparent memory leak in `fast_map_common_subexp()` - which c23373a didn't fix. I could see that to exercise `fast_map_common_subexp()` from Singular prompt, one  needs a call to `iiMap` (or `jjMAP`).
How does one trigger it?

**Comment by dimpase** [comment]
I suppose we can close this one, and move on to #1090.

**Comment by fingolfin** [comment]
@hannes14 close this?
