### ISSUE TITLE
nres over the integers

### ISSUE THREAD

**Issue by mohamed-barakat** [Singular/Singular#1101]
homalg uses `nres` instead of `syz` to get a shorter list of generating syzygies and it seems to work over fields but we have encountered bugs over ZZ as in the attached file. Is this a bug or a wrong usage of `nres`?

@kamalsaleh

[reduced_syzygies_singular.txt](https://github.com/Singular/Singular/files/6632997/reduced_syzygies_singular.txt)

**Comment by hannes14** [comment]
yes, minimizing (nres,mres, minres) uses Gauss, which requires field coeffficients.

**Comment by mohamed-barakat** [comment]
Thank you very much Hans. I will close the issue.
