### ISSUE TITLE
Optimization-dependent segfault in syzextra tests

### ISSUE THREAD

**Issue by orlitzky** [Singular/Singular#1105]
When `./configure --disable-optimizationflags` is used, compiling with `-O2` causes a segfault that was reported to us on Gentoo at https://bugs.gentoo.org/797655

By adding back the optimization flags one at a time, I found that `-fno-delete-null-pointer-checks` avoids the segfault. Specifically, `CXXFLAGS="-O2 -pipe -fno-delete-null-pointer-checks"` works fine while `CXXFLAGS="-O2 -pipe"`crashes.

Should that flag be required, or is it hiding a bug? I ask for two reasons... First, `-fno-delete-null-pointer-checks` is actually an _anti_-optimization if I read the GCC man page correctly. And second, if it's needed for singular to work correctly, shouldn't it be in `AM_CXXFLAGS` somewhere and not in a user-facing option?

**Comment by hannes14** [comment]
Yes, -fno-delete-null-pointer-checks is required. But we can move it to AM_CXXFLAGS,
see a227dd5004517d2b2b9e6756d7c49f28b9558530

**Comment by orlitzky** [comment]
Cool, thanks!
