### ISSUE TITLE
Segfault when using 'apply' with an empty list.

### ISSUE THREAD

**Issue by ureimaa** [Singular/Singular#1106]
Executing the line
 
apply( list() , x->{x} );

(or any other variation I tried involving 'apply' and the empty list) results in a segfault, although the expected result of the computation would be an empty list.

Non-empty lists work just fine.

Tested on: version 4.2.0 (Windows/Cygwin)
and on: version 4.2.1 (Linux/Ubuntu, from ftp://jim.mathematik.uni-kl.de/repo/ubuntu20)

> Singular : signal 11 (v: 4200):
current line:>>apply(list(),x->{x});<<
Segment fault/Bus error occurred (r:1625506502)
please inform the authors

**Comment by hannes14** [comment]
fixed with bfd7b5f1837153ed524ecbda78220c76bc32e6ab
