### ISSUE TITLE
docbuilding fails to find IntegerProgramming/ binaries

### ISSUE THREAD

**Issue by collares** [Singular/Singular#1123]
This happens with Singular 4.2.1p2 + b67904c91e15359f47b0d5e377ffe945a966c8ff. When running `make`, docbuilding fails with:
```
<lib intprog (d2t d2t_singular/intprog_lib.doc==>d2t_singular/intprog_lib.tex(solve_IP)
**** Error: while running example solve_IP from d2t_singular/intprog_lib.doc:85.
Call: '../Singular/Singular  -teqr12345678 --no-rc ./examples/solve_IP.sing > ./examples/solve_IP.res'
make[4]: *** [Makefile-docbuild:180: d2t_singular/intprog_lib.tex] Error 1
```
Running the example manually, I get the following error:
```
$ ../Singular/Singular  -teqr12345678 --no-rc ./examples/solve_IP.sing
./examples/solve_IP.sing   1> LIB "intprog.lib";
./examples/solve_IP.sing   2> // 1. call with single right-hand vector
./examples/solve_IP.sing   3. intmat A[2][3]=1,1,0,0,1,1;
./examples/solve_IP.sing   4> intvec b1=1,1;
./examples/solve_IP.sing   5> intvec c=2,2,1;
./examples/solve_IP.sing   6> intvec solution_vector=solve_IP(A,b1,c,"pct");
sh: line 1: /home/collares/source/Singular/.libs/solve_IP: No such file or directory
```

`feResource('r')` returns `/home/collares/source/Singular/.libs/..`, the configure flags are `--disable-static --prefix=/home/collares/nixpkgs/outputs/out --disable-pyobject-module --enable-doc-build --enable-gfanlib`, and the only `solve_IP` binary I have is in `/home/collares/source/IntegerProgramming/` (`Singular/.libs` only contains `Singular`, `ESingular`, `TSingular` and a bunch of libraries). A similar error occurs without b67904c91e15359f47b0d5e377ffe945a966c8ff, but the logic in b67904c91e15359f47b0d5e377ffe945a966c8ff looks like it was supposed to fix problems such as this one so I figured it would be relevant to apply it.

**Comment by collares** [comment]
Before the `SingularBin` change, there was a workaround (added to Makefile-docbuild.in in 012df22c6999ddce26c08a1a3c5f27474054a013) so docbuilding could find the `IntegerProgramming` binaries. After the `SingularBin` change in a14c91c0ced222f4ea5caf4b9627d02184fc72ac, I believe the previous workaround is now a no-op.

**Comment by hannes14** [comment]
fixed with https://github.com/Singular/Singular/commit/93315a26cf323cb99daaa70c9c54bc92771c6388

**Comment by collares** [comment]
Docbuilding works now. Thanks!
