### ISSUE TITLE
libparse build can't find fegetopt.c (spielwiese only)

### ISSUE THREAD

**Issue by collares** [Singular/Singular#1124]
See https://github.com/Singular/Singular/blob/spielwiese/Singular/Makefile.am#L190 and 3ad58c25ca404741a27daf824ff2e689f434bf2c:

```
  CXX      libparse-libparse.o
make[4]: *** No rule to make target 'fegetopt.c', needed by 'libparse-fegetopt.o'.  Stop.
make[4]: *** Waiting for unfinished jobs....
```

**Comment by hannes14** [comment]
fix with https://github.com/Singular/Singular/commit/175590237a3acf6df2c8581410e3ef8e125e99d6

**Comment by collares** [comment]
Works for me now. Thanks!
