### ISSUE TITLE
poly undefined on s390x

### ISSUE THREAD

**Issue by d-torrance** [Singular/Singular#1125]
I'm getting the following on a Debian unstable s390x porterbox:

```
                     SINGULAR                                 /  Development
 A Computer Algebra System for Polynomial Computations       /   version 4.2.1
                                                           0<
 by: W. Decker, G.-M. Greuel, G. Pfister, H. Schoenemann     \   May 2021
FB Mathematik der Universitaet, D-67653 Kaiserslautern        \  Debian 1:4.2.1-p2+ds-5
> ring r=32003,(x,y,z),dp;
> poly f=x3+y5+z2;
> f;
   ? `f` is undefined
   ? error occurred in or before STDIN line 3: `f;`
```
This isn't an issue in Debian testing, which still has singular 4.1.1.

This is causing a [QEPCAD continuous integration test](https://autopkgtest.ubuntu.com/results/autopkgtest-jammy/jammy/s390x/q/qepcad/20211216_201020_bda39@/log.gz) to fail, which in turn is preventing the singular package in Ubuntu 22.04 (the next LTS release) from [migrating](https://people.canonical.com/~ubuntu-archive/proposed-migration/update_excuses.html#singular) from "proposed" to "release".

Note that s390x is a big endian architecture, so that may be related.

**Comment by hannes14** [comment]
https://github.com/Singular/Singular/commit/5b75175f8fbf3cd70e54e8d04c9ee17545c5a04b
may help (cannot test it here).

**Comment by d-torrance** [comment]
It did indeed -- thank you!
