### ISSUE TITLE
No gpg file found

### ISSUE THREAD

**Issue by beew** [Singular/Singular#1169]
Hi, I am trying to install Singular with the apt repository following instructions here https://www.singular.uni-kl.de/index.php/singular-download/110.html but it couldn't find the gpg key

```
$ wget ftp://jim.mathematik.uni-kl.de/repo/extra/gpg
bash: wget ftp://jim.mathematik.uni-kl.de/repo/extra/gpg: No such file or directory
```
OS Ubuntu 22.04. Thanks

**Comment by hannes14** [comment]
This is an error message from bash: you have some (non-printable) characters between wget and ftp instead of space.
