### ISSUE TITLE
make install is broken in 4.3.2p2

### ISSUE THREAD

**Issue by antonio-rojas** [Singular/Singular#1176]
Commit 86ffd6a0082fd11304fe84e23f63b319b3da1c7c breaks `make install` in several ways:
- Removes $DESTDIR support, which breaks builds for packaging
- Duplicates ${prefix}. ${datadir} already includes ${prefix} by default, see [1]

[1] https://www.gnu.org/software/automake/manual/html_node/Standard-Directory-Variables.html

**Comment by hannes14** [comment]
should be fixed with 8d54773d6c9e2f1d2593a28bc68b7eeab54ed529

**Comment by antonio-rojas** [comment]
`make install` works fine with it, thanks.
```
 uninstall-local:
-	-(cd $(prefix)$(datadir); rm -rf singular info/singular.info)
+	-(cd $(prefix); rm -rf singular info/singular.info)
```
I don't use `make uninstall` myself, but shouldn't that be `cd $(datadir)`?

**Comment by hannes14** [comment]
Thanks, d1ec153efbb92b07a03c829a7f893fe854f169d2 should fix this.
