### ISSUE TITLE
Broken stuff on the website

### ISSUE THREAD

**Issue by fingolfin** [Singular/Singular#1195]
Some things I just noticed:
- front page has broken links to homepages of Greuel and Pfister
- front page links to https://www.singular.uni-kl.de/index.php/background/acknowledgements.html which has a broken image and claims Singular uses TeamCity (does it?)
- https://www.singular.uni-kl.de/index.php/third-party-software/software-using-singular.html has a broken link to Macaulay2
- https://www.singular.uni-kl.de/index.php/background/history.html has a spurious `< tr>` show up (note the extra space that should not be there)

Oh, and the certificate for https://www.singular.uni-kl.de:8003/ expired 5 October 2023

**Comment by hannes14** [comment]
fixed

**Comment by fingolfin** [comment]
Thank you! The `< tr>` on https://www.singular.uni-kl.de/index.php/background/history.html is still there, though

**Comment by fingolfin** [comment]
Actually, all issues are still present -- so I assume they are fixed in some internal repository or so, and we'll see the fixes with the next release or so?
