### ISSUE TITLE
Again bug in hilb with 136 indeterminates

### ISSUE THREAD

**Issue by mohamed-barakat** [Singular/Singular#1227]
When invoking hilb(gb,1) on the standard maximal ideal in 136 indeterminates the output is corrupted:

The string [1,58] appears in the output (see below).

This happens with the latest Singular a1c8d0a0@master:

                     SINGULAR                                 /  Development
 A Computer Algebra System for Polynomial Computations       /   version 4.4.0
                                                           0<
 by: W. Decker, G.-M. Greuel, G. Pfister, H. Schoenemann     \   Apr 2024
FB Mathematik der Universitaet, D-67653 Kaiserslautern        \
> ring r = (0),(x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x19,x20,x21,x22,x23,x24,x25,x26,x27,x28,x29,x30,x31,x32,x33,x34,x35,x36,x37,x38,x39,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49,x50,x51,x52,x53,x54,x55,x56,x57,x58,x59,x60,x61,x62,x63,x64,x65,x66,x67,x68,x69,x70,x71,x72,x73,x74,x75,x76,x77,x78,x79,x80,x81,x82,x83,x84,x85,x86,x87,x88,x89,x90,x91,x92,x93,x94,x95,x96,x97,x98,x99,x100,x101,x102,x103,x104,x105,x106,x107,x108,x109,x110,x111,x112,x113,x114,x115,x116,x117,x118,x119,x120,x121,x122,x123,x124,x125,x126,x127,x128,x129,x130,x131,x132,x133,x134,x135,x136),(dp,c);

> matrix mat[1][136] = x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x19,x20,x21,x22,x23,x24,x25,x26,x27,x28,x29,x30,x31,x32,x33,x34,x35,x36,x37,x38,x39,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49,x50,x51,x52,x53,x54,x55,x56,x57,x58,x59,x60,x61,x62,x63,x64,x65,x66,x67,x68,x69,x70,x71,x72,x73,x74,x75,x76,x77,x78,x79,x80,x81,x82,x83,x84,x85,x86,x87,x88,x89,x90,x91,x92,x93,x94,x95,x96,x97,x98,x99,x100,x101,x102,x103,x104,x105,x106,x107,x108,x109,x110,x111,x112,x113,x114,x115,x116,x117,x118,x119,x120,x121,x122,x123,x124,x125,x126,x127,x128,x129,x130,x131,x132,x133,x134,x135,x136;
> matrix gb = std(mat);

> ncols(gb);

136

> hilb(gb,1);

// ** _ is no standard basis
1,-136,9180,-410040,13633830,-359933112,7858539612,-145944307080,2353351951665,-33469894423680,425067659180736,-4868956823342976,50718300243156000,-483774556165488000,4250305029168216000,-34569147570568156800,261429178502421685800,-1845382436487682488000,12200028330113012004000,-75768596997543969288000,443246292435632220334800,-2448408091549206550420800,12798496842189034240836000,-63436027826502169715448000,298677964349781049076901000,-1338077280287019099864516480,5712560696609966157113897280,-23273395430633195454908470400,90600003640679225163750831200,-337406910110115735092589302400,1203417979392746121830235178560,-4114913090826809319806610610560,13502058579275468080615441065900,-42551942189231778193454723359200,128907354279143328056642250176400,-375672861042074841765071700514080,1053971082368043306063117826442280,-2848570492886603529900318449844000,7421275757783519722635040171962000,-18648333955456023918416254791084000,45222209841980858002159417868378700,-105886149873906399224568393057667200,239504386619550188722238031916152000,-523567728889249249764892441863216000,1106631790606822277912159024847252000,-2262447216351725545953747339687715200,4475710797565370101778065389382219200,-8570510037891134237447359256263824000,15891154028589811398600311954322507000,-28539215398283742919935254122048584000,49658234793013712680687342172364536160,-83737415533317240990962969153399021760,136878467698691643927535622654594554800,-216939458239435813017226269867659294400,333443982108762453341292229611402248800,-497134664234882203163381142329726989120,719069782196883186718462009441212252120, **[1,58]**,1374628258767181409576733181992880046400,-1817305155658307626220087935516010908800,2332208283094828120315779517245547332960,-2905702123200113723672118742797731103360,3514962245806589181861433963061771496000,-4128685812534723800916604972485255408000,4709282254922419335420502546740994449750,-5216435728529449110004248974851563082800,5611620253418043739550025412340317861800,-5862886831929299429380623565131675378000,5949105755928259715106809205795376486500,-5862886831929299429380623565131675378000,5611620253418043739550025412340317861800,-5216435728529449110004248974851563082800,4709282254922419335420502546740994449750,-4128685812534723800916604972485255408000,3514962245806589181861433963061771496000,-2905702123200113723672118742797731103360,2332208283094828120315779517245547332960,-1817305155658307626220087935516010908800,1374628258767181409576733181992880046400,-1009220746942993946271525627285911932800,719069782196883186718462009441212252120,-497134664234882203163381142329726989120,333443982108762453341292229611402248800,-216939458239435813017226269867659294400,136878467698691643927535622654594554800,-83737415533317240990962969153399021760,49658234793013712680687342172364536160,-28539215398283742919935254122048584000,15891154028589811398600311954322507000,-8570510037891134237447359256263824000,4475710797565370101778065389382219200,-2262447216351725545953747339687715200,1106631790606822277912159024847252000,-523567728889249249764892441863216000,239504386619550188722238031916152000,-105886149873906399224568393057667200,45222209841980858002159417868378700,-18648333955456023918416254791084000,7421275757783519722635040171962000,-2848570492886603529900318449844000,1053971082368043306063117826442280,-375672861042074841765071700514080,128907354279143328056642250176400,-42551942189231778193454723359200,13502058579275468080615441065900,-4114913090826809319806610610560,1203417979392746121830235178560,-337406910110115735092589302400,90600003640679225163750831200,-23273395430633195454908470400,5712560696609966157113897280,-1338077280287019099864516480,298677964349781049076901000,-63436027826502169715448000,12798496842189034240836000,-2448408091549206550420800,443246292435632220334800,-75768596997543969288000,12200028330113012004000,-1845382436487682488000,261429178502421685800,-34569147570568156800,4250305029168216000,-483774556165488000,50718300243156000,-4868956823342976,425067659180736,-33469894423680,2353351951665,-145944307080,7858539612,-359933112,13633830,-410040
,9180,-136,1,0
>
Auf Wiedersehen.

**Comment by hannes14** [comment]
Printout to the terminal (as here) tries to format the output, exchanging too long members by *[..,..]*.
The considered string length depends on the variable pagewidth.
To get the complete values of hilb(..,1) as a string use "string(hilb(gb,1));"

**Comment by mohamed-barakat** [comment]
Wonderful, works. Thank you very much @hannes14.
