### ISSUE TITLE
nr2mGreater is weird

### ISSUE THREAD

**Issue by user202729** [Singular/Singular#1253]
Currently for a polynomial ring with coefficient modulo 2^m for small m, then `cfGreater` is set to `nr2mGreater(a, b)`, which checks if `a` is divisible by `b`.

This is weird because it means every number is greater than itself.

Suggestion: change it to something more sensible. For comparison:

* `nrnGreater` does the following

	```cpp
	static BOOLEAN nrnGreater(number a, number b, const coeffs)
	{
	  return 0 < mpz_cmp((mpz_ptr)a, (mpz_ptr)b);
	}
	```

* `nfGreater` does the following

	```cpp
	/*2
	* a > b ?
	*/
	static BOOLEAN nfGreater (number a,number b, const coeffs r)
	{
	#ifdef LDEBUG
	  nfTest(a, r);
	  nfTest(b, r);
	#endif
	  return (long)a != (long)b;
	}
	```

There is a recommendation

```
/// !!! Recommendation: remove implementations for unordered fields
/// !!!                 and raise errors instead, in these cases
static FORCE_INLINE BOOLEAN n_Greater(number a, number b, const coeffs r)
{ assume(r != NULL); assume(r->cfGreater!=NULL); return r->cfGreater(a,b,r); }
```

but sometimes it is useful to have a comparison e.g. for sorting and binary searching.
For example `SageMath`'s polynomial comparison relies on this method at the moment (which leads to it being intransitive).

I think the comparison should define some total order, even if it doesn't make sense mathematically. `nrnGreater` currently does that.

Furthermore, the comparison returned by `nfGreater` should be consistent with `nfGreaterZero`.

**Comment by hannes14** [comment]
concerning nfGreaterZero:     
  //GreaterZero is used for printing of polynomials:
       //  a "+" is only printed in front of a coefficient
       //  if the element is >0. It is assumed that any element 
       //  failing this will start printing with a leading "-"
(from libpolys/coeffs/coeffs.h)
