### ISSUE TITLE
Singular 4.0.0 is missing documentation

### ISSUE THREAD

**Issue by fingolfin** [Singular/Singular#459]
With previous Singular releases, there used to be a separate -share tarball which contained the manual and various help files, making it possible to view the documentation online.

This seems to be not anymore the case with 4.0.0 :/. Not nice (and I'd like to request it being re-added), but if that was an intentional decision of the Singular team, I am sure you had good reasons for it...

But there are other ramifications that look like a bug. For example, starting ESingular displays an error message: it is looking for a file `@prefix@/share/info/singular.hlp` which used to be provided by the -share tarball -- now I can't find a trace of it in the Singular 4.0.0 tarball. And "make && make install" neither builds it nor installs it.

So, something is fishy there...

**Comment by matzeri** [comment]
The current singular-4.0.2-share.tar.gz includes also "share/singular/LIB"
that is already installed with "make install". 
So I am currently forced to untar it, before "make install" from git source to avoid any change in LIB
is lost.

Of course a proper make doc / make install-doc, will be appreciated.
