### ISSUE TITLE
Singular fails "make check" on Ubuntu 14.04.1

### ISSUE THREAD

**Issue by fingolfin** [Singular/Singular#642]
I compiled revision a12d11c1f4feecd on an Ubuntu 14.04.1 machine, as part of SingularInterface. That is, I did an out of tree build, with sources in `singular/src`, build files in `singular/build`, and install destination `singular/dst`

Doing `make check` I get this output (truncated):

```
Making check in xalloc
make[1]: Entering directory `/PATH/TO/singular/build/xalloc'
make[1]: Nothing to be done for `check'.
make[1]: Leaving directory `/PATH/TO/singular/build/xalloc'
Making check in factory
make[1]: Entering directory `/PATH/TO/singular/build/factory'
make  check-recursive
make[2]: Entering directory `/PATH/TO/singular/build/factory'
Making check in include/factory
make[3]: Entering directory `/PATH/TO/singular/build/factory/include/factory'
make[3]: Nothing to be done for `check'.
make[3]: Leaving directory `/PATH/TO/singular/build/factory/include/factory'
make[3]: Entering directory `/PATH/TO/singular/build/factory'
[ -d ./gftables ] || ln -s ../../src/factory/gftables .
make  test
make[4]: Entering directory `/PATH/TO/singular/build/factory'
  CXXLD    test
/usr/bin/ld: test.o: undefined reference to symbol '_Z15feInitResourcesPKc'
/PATH/TO/singular/dst/lib/libresources-4.0.0.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[4]: *** [test] Error 1
```

**Comment by jgmbenoit** [comment]
For information, singular 4.0.1 has been brought to Debian: at the time of writing the package is in the NEW queue, neverthless it can be fetched from its git repository at Alioth.

**Comment by malex984** [comment]
We are currently preparing to release Singular 4-0-2 
(http://www.mathematik.uni-kl.de/ftp/pub/Math/Singular/SOURCES/4-0-2/ or current git HEAD). 
Could you please treat it as well?

**Comment by malex984** [comment]
https://ftp-master.debian.org/new/singular_4.0.1p2+ds-1.html looks really nice. Thanks!

Besides could you please consider adding/moving libsingular-config, libpolys-config libpolys/misc/auxiliary.h, factory/cplusplus.h (and maybe factory/cf_gmp.h) to libsingular4-dev?

**Comment by malex984** [comment]
@jgmbenoit https://ftp-master.debian.org/new/singular_4.0.1p2+ds-1.html looks really nice. Thanks! 
Besides could you please consider adding/moving libsingular-config, libpolys-config libpolys/misc/auxiliary.h, factory/cplusplus.h (and maybe factory/cf_gmp.h) to libsingular4-dev?

**Comment by jgmbenoit** [comment]
I am on my way to treat singular 4.0.2 and futur version.
I am packaging some depencies right now.

**Comment by jgmbenoit** [comment]
@malex984 concerning the suggested adding/moving:
1] the lib<WHATEVER>-config are not deliberatley added, see  https://lists.debian.org/debian-science/2015/03/msg00027.html for the why;
2] the list of the headers meant for development are not modifed, what is modified is the place of the include folder (see the previous cited email for the why), so there absence are more likely an upstream bug somewhere in the involved Makefile.am.

Saying that, would it be possible to add the bison/flex source files in the upstream source tarball ?
