### ISSUE TITLE
lex: please specify how to generate S/libparse.{h,cc} and S/scanner.cc

### ISSUE THREAD

**Issue by jgmbenoit** [Singular/Singular#760]
Please specify how to generate Singular/libparse.{h,cc} from Singular/libparse.ll , and Singular/scanner.cc from Singular/scanner.ll .
I noticed that there is a Singular/make_grammar script for generating Singular/grammar.{h,cc} from Singular/grammar.yy , but I cannot find anything similar for S/libparse.{h,cc} and S/scanner.cc .
BTW, is Singular/libparse.sed still relevant ?

**Comment by hannes14** [comment]
Singular/make_scanner_libparse
