### ISSUE TITLE
Release 4.1.3 isn't tagged in the GitHub repository

### ISSUE THREAD

**Issue by yurivict** [Singular/Singular#998]

**Comment by fingolfin** [comment]
@hannes14 added two previously missing tags: `Release-4-1-3` and `Release-4-1-3p2`.

So I guess this can be closed now?

**Comment by fingolfin** [comment]
I've submitted issue #1023 now, which would help avoid this kind of problem in the future. In any case, this issue can be closed now.

**Comment by fingolfin** [comment]
@hannes14 close this?
