### ISSUE TITLE
Rename this repository to Singular

### ISSUE THREAD

**Issue by fingolfin** [Singular/Singular#999]
I suggest that https://github.com/Singular/Sources be renamed to https://github.com/Singular/Singular -- the current setup is rather confusing.

Note that GitHub will automatically redirect the old to the new URL, so existing scripts or clones of the repository will keep working

**Comment by fingolfin** [comment]
One motivation for this is that e.g. forks will have a clearer name: https://github.com/fingolfin/Sources conveys no information as to what the repository contains, but https://github.com/fingolfin/Singular does.

Since GitHub redirects almost everything, I see no downside to this. @hannes14 @fieker any thoughts?

**Comment by fieker** [comment]
On Wed, Jun 17, 2020 at 02:26:07AM -0700, Max Horn wrote:
> One motivation for this is that e.g. forks will have a clearer name: https://github.com/fingolfin/Sources conveys no information as to what the repository contains, but https://github.com/fingolfin/Singular does.
> 
> Since GitHub redirects almost everything, I see no downside to this. @hannes14 @fieker any thoughts?
> 

Be my guest...

**Comment by hannes14** [comment]
Agreed.

**Comment by fingolfin** [comment]
I do not have admin permissions, so I cannot make that change :-)

**Comment by hannes14** [comment]
renamed to https://github.com/Singular/Singular
